# Local environment settings
port: 80

# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "mIGUELfITO"
description: > # this means to ignore newlines until "email:"
    A mess evolved into disaster

email: miguelfito@gmail.com
#blog logo
logo: "/assets/images/mf_logo.png"
# blog cover
cover: "/assets/images/background_image.jpg"

name: 'Miguel Á. Melón'
author: 'Miguel Ángel Melón'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://blog.miguelfito.com" # the base hostname & protocol for your site
baseurl: ""

# Google Analytics
google_analytics: "UA-21772482-5"

# Disqus
disqus: "blog-miguelfito"

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/miguelfito
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/miguel.melon
    desc: Connect with me facebook
    share_url: //www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/miguelfito
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
